---
- hosts: local
  connection: local
  gather_facts: False
  vars:
    instance_type: t2.small
    security_group: ssh
    image: ToBeDefinedYet
    keypair: keys 
    region: us-east-1
    count: 1
  vars_files:
      # to contain encrypted secrets, not included
    - awskeys.yml

tasks:
    - name: Create a security group
      ec2_group:
        name: "{{ security_group }}"
        description: The webservers security group
        region: "{{ region }}"
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        rules:
          - proto: tcp
            from_port: 2222
            to_port: 22
            cidr_ip: 0.0.0.0/0
        rules_egress:
          - proto: all
            cidr_ip: 0.0.0.0/0

   - name: Launch the new EC2 Instance
         ec2:
           aws_access_key: "{{ aws_access_key }}"
           aws_secret_key: "{{ aws_secret_key }}"
           group: "{{ security_group }}"
           instance_type: "{{ instance_type }}"
           image: "{{ image }}"
           wait: true 
           region: "{{ region }}"
           keypair: "{{ keypair }}"
           count: "{{count}}"
         register: ec2

    - name: Add tag to Instance(s)
      ec2_tag:
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        resource: "{{ item.id }}" 
        region: "{{ region }}" 
        state: "present"
      with_items: "{{ ec2.instances }}"
      args:
        tags:
          env: task


